### ISSUE TITLE
project proposal: care to do this for NASTY optimization problems?

### ISSUE THREAD

**Issue by timm** [tdgoodrich/fss16tdg#1]
doing this for DTLZ1 etc is kinda yaaawn

care to do it for NASTY problems? e.g. the ones listed in http://arxiv.org/abs/1608.07617?

if you look at fig9 fig10 then 
- the easier models are on top (in fig9, the pom stuff is harder than {osp,osp2,flight,ground)
- the harder models are below (fig10 harder than fig9 and the bottom half of fig10 harder than the top half)

thing is, i know what is easy/hard here cause i've run them all. long tedious runs. but is there some way to peek at them very early one to get a sense of "oh dear... this is gonna be a hard one?"

if you are interested in this one, i need to team you up with vievk and jianfeng (the folks who write this paper).

**Comment by tdgoodrich** [comment]
Project direction changed
